### PR TITLE
Filter out k8s objects that belong to Helm

### LINKED ISSUE #7384: Cluster deployments Helm v2 -> v3 migration made traefik crash with OOMKill
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We have migrated all the deployments of a Kubernetes cluster from helm v2.x to v3.x (traefik itself is **not** deployed with Helm).

Helm v2 used to store Helm "releases" using **ConfigMaps**. In Helm v3 the "releases" are stored using **Secrets**.

The contents of theses new Secrets (we had around 700 of them) are quite large binaries (at least hundreds of KiB, but lesser than 1MiB which is kubernetes/etcd limitation) and it seems that Traefik downloads them all from Kubernetes and keeps them in memory (or at least it does not have time to discard them before it is killed).

FYI before we made the migration the memory limit for Traefik pods was 512Mi and we never had a problem. We had to increase it to 2Gi to make it work until we understood where the memory consumption was coming from.

For the record Helm v2 made the `nginx-ingress-controller` behave quite similarly (OOMkilled because it reached the limit) because it was downloading all the clusters ConfigMaps including all the ones storing Helm v2 releases. The following patch was merged to avoid downloading Helm related ConfigMaps any longer https://github.com/kubernetes/ingress-nginx/pull/5702. Note that this would not work as it for Traefik and Helm v3 Secrets as it seems that Helm v3 Secret labeling use `owner=helm` instead of `OWNER=TILLER`, i don't know if the filtering is case sensitive. 

### What did you expect to see?

I would have expected that traefik does not fetch all the secrets from the Kubernetes api-server, only the ones it needs.

### What did you see instead?

Traefik being killed because it consumes too much memory.

### Output of `traefik version`: (_What version of Traefik are you using?_)

[v2.2.1+sylr.1](https://github.com/sylr/traefik/commits/v2.2.1%2Bsylr.4)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    [log]
      level = "INFO"
      format = "json"
    #[tracing]
    #  [tracing.instana]
    #    localAgentHost = "instana-agent.instana.svc.cluster.local."
    #    localAgentPort = 42699
    #    logLevel = "info"
    [accessLog]
      format = "json"
      [accessLog.fields]
        defaultMode = "keep"
      [accessLog.fields.names]
        ClientAddr = "drop"
        RequestAddr = "drop"
      [accessLog.fields.headers]
        [accessLog.fields.headers.names]
          "User-Agent" = "keep"
    [entryPoints.http]
      address = ":80"
    [entryPoints.http-internal]
      address = ":81"
    [entryPoints.https]
      address = ":443"
    [entryPoints.traefik]
      address = ":8080"
    [entryPoints.traefik-ext]
      address = ":8081"
    [providers.kubernetesIngress]
      ingressClass = "traefik-v2"
    [providers.kubernetesCRD]
    [providers.file]
      directory  = "/config/static"
      watch = true
    [api]
      insecure = true
      dashboard = true
      debug = true
    [metrics.prometheus]
      entryPoint = "traefik"
      buckets = [0.1,0.25,0.5,0.75,1.0,1.5,2.0]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by sylr**
### What does this PR do?

Filter out kubernetes secret generated by Helm v3 which contains large binary data.

### Motivation

Fix #7384, #7406

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Banners_and_Alerts_and_Prometheus_Time_Series_Collection_and_Processing_Server

### CODE REVIEW

**Comment by rtribotte** [comment]
Hello @sylr,

Thanks for your contribution !

As a first lookup, i can say that a fixed labelSelector excluding for all informers the helm resources is not something that we will accept, because it's one use case.

Also, i wonder why you don't use the configurable label selector from the client to filter out the resources ?

**Comment by rtribotte** [comment]
Re @sylr 

I forgot, but can you please rebase your PR to the v2.3 ?

**Comment by sylr** [comment]
> As a first lookup, i can say that a fixed labelSelector excluding for all informers the helm resources is not something that we will accept, because it's one use case.

OK, I can understand that, I try another approach.

> Also, i wonder why you don't use the configurable label selector from the client to filter out the resources ?

Because the labelSelectors in traefik's kubernetes/kubernetesCDR providers configuration are only applied once traefik has received the objects from the api-server, it's too late as it is already in memory.

The next patch iteration will fix that.

> I forgot, but can you please rebase your PR to the v2.3 ?

I believe the problem is severe enough to be fixed at least on the v2.2 line. Once something is accepted in v2.2 i'll merge it into v2.3.

**Comment by ldez** [comment]
We only maintain one minor version, so we will not create a fix release on v2.2.

https://github.com/traefik/traefik#release-cycle

So could you rebase on v2.3, thank you.

**Comment by jbdoumenjou** [comment]
Hi @sylr,

We think that using the labelSelector as tweakListOptions for K8s Ingress and CRD Provider is a good idea, therefore we created a specific PR #7521.
In the same way, we think that it will be simpler to add only one hardcoded labelSelector with "owner!=helm" (from Helm [doc](https://helm.sh/docs/topics/advanced/#configmap-storage-backend)) as tweakListOptions on the `Secret` informer both for the Ingress and CRD providers. With that solution, we only filter Secrets created by Helm Chart. WDYT?

**Comment by sylr** [comment]
I think it would have been more considerate to ask me first before doing a parallel PR which will ultimately make this one obsolete and consequently make the time I spent working on it worthless ...

Anyhow, I'm all for applying label selection to all objects but this is a breaking change so not mergeable on the current 2.3 branch. This patch however is transparent in term of discovery.

**Comment by jbdoumenjou** [comment]
Hi @sylr, thanks for your feedback.

The other PR applies the filter only to the Traefik CRD Objects and Ingresses.
Moreover, the other PR is based on master so you don't have to rebase your branch on it.

Concerning this fix, as we already mentioned, having one specific filter as tweakListOptions with a labelselector "owner=helm" only on the secrets informer will avoid excessive memory usage.

**Comment by sylr** [comment]
> The other PR applies the filter only to the Traefik CRD Objects and Ingresses.

That is a breaking change that can not be applied on current v2.3 branch.

> Moreover, the other PR is based on master so you don't have to rebase your branch on it.

I've already been asked to rebase from 2.2 to 2.3 so it is not really a problem.

> Concerning this fix, as we already mentioned, having one specific filter as tweakListOptions with a labelselector "owner=helm" only on the secrets informer will avoid excessive memory usage.

And that's what I did the with the first iterations of this patch and then I thought about it and decided to filter secrets using their type rather than labels because Traefik has no business retrieving secrets with types it has no use for. This will avoid more troubles if the labels of helm change again or if another component start using kubernetes Secrets has data source.

**Comment by jbdoumenjou** [comment]
We think that the fix on v2.3 with a labelselector is enough as a first step, if helm changes the label, or if another issue comes, we will update the code accordingly.

Can you update the PR in that way?

Thanks

**Comment by sylr** [comment]
> Can you update the PR in that way?

No, I'm good, I stand by my fix.

**Pull request closed without merging**
