### PR TITLE
Bump quic-go from v0.33.0 to v0.37.4

### PR DESCRIPTION
**Pull request by stefanb**
### What does this PR do?

Bump quic-go from v0.33.0 to v0.37.4 for Go 1.21 support, see
* https://github.com/quic-go/quic-go/releases/tag/v0.37.4
* https://github.com/quic-go/quic-go/releases

### Motivation

Compatibility with current Go version
* https://github.com/traefik/traefik/issues/10075 

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Supported Go versions are 1.20 and 1.21
Go 1.19 and older are not supported anymore.

### CODE REVIEW

**Comment by ldez** [comment]
You are not targeting the right branch, could you rebase your branch onto v2.10 branch?

**Comment by ldez** [comment]
Is it a problem for you if I close your PR in favor of my PR #10078?
It is just easier for me.

**Comment by stefanb** [comment]
Sure, go ahead, i had similar prepared first: https://github.com/traefik/traefik/compare/master...stefanb:traefik:go-1.21
...but decided to break it down into two smaller PRs after reading your contribution guidelines :)

**Comment by ldez** [comment]
Thank you anyway :heart:

**Pull request closed without merging**
