### PR TITLE
updating docs to remove a no longer needed note

### LINKED ISSUE #7924: Documentation middlewares/headers removing headers possible through label
### What did you do?
I needed to remove a response header. [The documentation](https://doc.traefik.io/traefik/middlewares/headers/) mentions the following:
> Please note that it is not possible to remove headers through the use of labels (Docker, Rancher, Marathon, ...) for now.

Either I am misinterpreting the warning or this limitation has been removed.
I have added the following label in my `docker-compose.yml`:  
`traefik.http.middlewares.my-middleware-header.headers.customresponseheaders.X-The-Header-To-Remove=`  
Which removed the header.

I would have submitted a PR to fix the docs but this might need some verification as I have only been able to test this through Docker. Not sure if the same goes for Rancher, Marathon, etc.

### Traefik version
v2.4.5

### PR DESCRIPTION
**Pull request by cmcga1125**
### What does this PR do?

This pull request removes a note referenced in issue #7924

### Motivation

I'd like to get involved in an open source project, i use Traefik at work a-lot and thought i'd liek to contribute.  also selfishly - i'd like to draw attention to my comment on issue [6322](https://github.com/traefik/traefik/issues/6322) and show i'd be happy to help document the kubernetes uses of Traefik, with a little support :).

Closes #7924

### More

- [x] Added/updated documentation

### Additional Notes

nice to meet you :)

### CODE REVIEW

**Comment by jbdoumenjou** [comment]
Hello @cmcga1125,

Thanks for your contribution.
Could you rebase your PR on the v2.4 branch?

**Comment by cmcga1125** [comment]
welp, i rebased incorrectly. i'll cut a new branch :p

**Review by SantoDE — APPROVED** [review]
LGTM 👼

**Review by dtomcej — APPROVED** [review]
LGTM
:shipit:

**Comment by cmcga1125** [comment]
Thanks everyone! how can i get more involved?  I'd like to help document kubernetes things if there's interest and maybe pick u p some easier coding tasks.  I know go a little bit and would like the opportunity to improve :-P

sorry to attach this to a PR just not sure where to ask 🙃

**Review by jbdoumenjou — APPROVED** [review]
LGTM

**Comment by jbdoumenjou** [comment]
@cmcga1125,

Thanks for your contribution.

Any help is welcome, would it be either for the documentation or the code.

You can work on issue with label [`contributor/good-first-issue`](https://github.com/traefik/traefik/issues?q=is%3Aopen+is%3Aissue+label%3Acontributor%2Fgood-first-issue), [`kind/enhancement`](https://github.com/traefik/traefik/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fenhancement), and read the contributions [documents](https://doc.traefik.io/traefik/v2.4/contributing/submitting-pull-requests/).
Another way to help us is to provide a reproducible case for [`kind/bug/possible`](https://github.com/traefik/traefik/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fbug%2Fpossible).

**Pull request merged**
