### PR TITLE
Add Marathon api query parameters support

### PR DESCRIPTION
**Pull request by genadipost**
### What does this PR do?

This PR adds the adds support for Marathon query parameters  (#7736).

### Motivation

Reduce the amount of data sent by Marathon.
Add the option to do most of the filtering during the Marathon application query instead of pulling all the application and filtering in memory.

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### CODE REVIEW

**Comment by genadipost** [comment]
Travis CI seems to fail on docker pull.

**Comment by genadipost** [comment]
I tried to re-trigger the build by force pushing, but Travis build keeps failing on the docker build.

````
$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make docs; fi
make -C ./docs docs
make[1]: Entering directory `/home/travis/build/traefik/traefik/docs'
rm -rf /home/travis/build/traefik/traefik/docs/site
docker build -t traefik-docs -f docs.Dockerfile ./
Sending build context to Docker daemon  6.536MB
Step 1/6 : FROM alpine:3.12
3.12: Pulling from library/alpine
age configuration: unexpected EOF
make[1]: *** [docs-image] Error 1
make[1]: Leaving directory `/home/travis/build/traefik/traefik/docs'
make: *** [docs] Error 2
````

Will be happy to get some help and understand the root cause.

**Comment by kevinpollet** [comment]
Hello @genadipost and thanks for your contribution,

We are having some issues with Travis CI these days.
Nothing wrong on your side, I have restarted the build, and everything is fine 😄 

This PR has been labelled as `needs-design-review`. As you can see in our [contribution guide](https://github.com/traefik/contributors-guide/blob/master/review_guidelines.md), this means that we have to take a closer look at the scope and impacts, to see how it would interact with the other parts of Traefik.

**Comment by genadipost** [comment]
Any ETA on the review?

**Comment by tfny** [comment]
Hey @genadipost, Thanks for hanging in there. 

We just completed the design review and have decided to not merge this PR.  Upon review, we realized that marathon just isn't used very much by our users (>.15%) and we believe that we will be removing it in Traefik Proxy 3.0, so merging it for 2.9 would not make much sense.

**Pull request closed without merging**
