### PR TITLE
Fix UI unit tests

### LINKED ISSUE #10640: Fix UI unit tests
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

**Motivation**
As a Traefik Frontend Developer I want to unit test the changes in webui project

I got the following output when I try to run unit tests for webui project
```bash
xxxxxxxxxxxxxxx :: personal/traefik/webui » yarn run test-unit
yarn run v1.22.19
$ mocha-webpack --mode=production './src/**/*.spec.js'
/bin/sh: 1: mocha-webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by framebassman**
### Motivation

This PR should close #10640 

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

- Base tutorial for unit test for the quasar framework - https://quasar.dev/quasar-cli-vite/testing-and-auditing#tutorials
- The unit test options are here - https://github.com/quasarframework/quasar-testing/tree/dev?tab=readme-ov-file

### CODE REVIEW

**Comment by framebassman** [comment]
Fix for #10640

**Comment by nmengin** [comment]
Hello @framebassman,

Thank you for your contribution.
Before moving forward, I'd like to have @gndz07 and @mdeliatf's opinions.

They are working as front-end developers at Traefik Labs and will have more relevant input than mine 😅

**Comment by framebassman** [comment]
@nmengin btw I think that these chages could be delivered to v2.11 branch without any issues cause the diff is the same. What do you think?

**Comment by framebassman** [comment]
cc @ldez to the previous comment

**Comment by nmengin** [comment]
Hey @framebassman,

> I think that these chages could be delivered to v2.11 branch 

As it's _only_ tests changes I guess you are right.
If you agree, I'd like to wait for more input from @gndz07 and @mdeliatf before changing the base branch.

**Pull request closed without merging**
