### PR TITLE
Fix incorrect syntax in yaml config examples

### PR DESCRIPTION
**Pull request by JokerQueue**
### What does this PR do?

Fix incorrect syntax in yaml config examples

### Motivation

Documentation fixes

### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### CODE REVIEW

**Comment by ldez** [comment]
Duplicate #7319

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Comment by ldez** [comment]
You don't need to update your PR, we have a bot for that.

**Comment by JokerQueue** [comment]
> You don't need to update your PR, we have a bot for that.

OK, thanks!

**Review by rtribotte — APPROVED** [review]
LGTM 👌

**Review by jbdoumenjou — APPROVED** [review]
LGTM

**Pull request merged**
