### PR TITLE
Set kubernetes client User-Agent to something meaningful

### LINKED ISSUE #7391: Tune k8s providers clients user agent
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The user agent used to talk to kubernetes is currently set to the default value which looks like this (taken from the k8s api-server metrics).

Fullscreen_07_10_2020_09_31

Tuning this could improve our ability to observe traefik's behavior towards the api-server by:

- having a correct version number
- differentiating the ingress from the crd provider

I'm currently crafting a PR.

### PR DESCRIPTION
**Pull request by sylr**
### What does this PR do?

Fix #7391

### Motivation

Better observability of k8s providers clients.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by sylr** [comment]
Could someone relaunch the trigger ?

**Review by jbdoumenjou — APPROVED** [review]
LGTM

**Review by kevinpollet — APPROVED** [review]
LGTM

**Review by dtomcej — APPROVED** [review]
LGTM
:shipit:

**Pull request merged**
