### PR TITLE
Fix typo in server transports documentation

### PR DESCRIPTION
**Pull request by obezuk**
### What does this PR do?
Corrects a typo in the documentation

### Motivation
3 hours of debugging

### CODE REVIEW

**Review by rtribotte — APPROVED** [review]
LGTM 👍

**Review by kevinpollet — APPROVED** [review]
LGTM

**Review by SantoDE — APPROVED** [review]
LGTM 👼 

Sorry for your long debugging for that ;)

**Review by jbdoumenjou — APPROVED** [review]
Thanks! :+1:

**Pull request merged**
