### PR TITLE
Fix blank webui on some browsers

### PR DESCRIPTION
**Pull request by matthieuh**
### What does this PR do?

Avoid to use `semver-regex` which fail on some browsers.

### Motivation

Fix https://github.com/traefik/traefik/issues/7357

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by obeyler** [comment]
@matthieuh may there is another pb as a get is done on Pilot url whereas the pilot is not enabled in the config

**Review by rtribotte — APPROVED** [review]
LGTM 👌

**Review by jbdoumenjou — APPROVED** [review]
LGTM :+1:

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
