### PR TITLE
Mitigate memory leak

### PR DESCRIPTION
**Pull request by mpl**
### What does this PR do?

This PR bumps the mux dependency version, because it contains a work-around to mitigate a memory leak.

### Motivation

To fix a memory leak, which might be the one observed at #7964 for example.

### More

~- [ ] Added/updated tests~
~- [ ] Added/updated documentation~

### Additional Notes

#8044, #7533

### CODE REVIEW

**Review by rtribotte — APPROVED** [review]
LGTM 👌

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by tomMoulard — APPROVED** [review]

**Comment by darkl0rd** [comment]
Is this also affecting Traefik 1.7? And if so, will this be backported? (#7191)

**Comment by llussy** [comment]
Hi, is there a fix for version 1.7? I didn't find a newer version.

**Comment by tfny** [comment]
We are looking into it, we will get back to you soon. :)

**Comment by ddtmachado** [comment]
@darkl0rd @llussy Just to clarify version 1.7 is not supported anymore and we are preparing a new doc section that would make it easy to find what versions we are actively maintaining and what are the rules for that, including exceptions if any.

The PR is still under review, and feedback is welcomed as always.

Having said that, yes this problem affects 1.7 and we might look at backporting it at some point if really needed. Really needed in this context means a customer is affected and couldn't finish the migration to 2.x in time or hit some blocker in doing so, then we might consider a priority to avoid production issues until the migration is finished.

Of course if someone in the community is willing to work on it and backport the fix into 1.7 I see no reason why we would not review and merge it as soon as possible.

**Pull request merged**
