### PR TITLE
Fixing doc for default value of checknewversion

### LINKED ISSUE #7878: unwanted check new version
### bug

--global.checknewversion arg was not set and so on regarding the documentation it should be define to false
 but I can see on my log :
```
time="2021-02-09T08:45:13Z" level=warning msg="Error checking new version: Get \"https://update.traefik.io/repos/traefik/traefik/releases\": dial tcp 104.26.2.101:443: i/o timeout"
```

args use on our deployment in K8S
```
              args:
              - --api=true
              - --api.dashboard=true
              - --log.level=INFO
              - --accesslog=true
              - --global.sendanonymoususage=false
              - --providers.kubernetescrd=true
              - --providers.kubernetescrd.allowcrossnamespace=false
              - --entrypoints.web=true
              - --entryPoints.web.address=:8000
              - --entrypoints.websecure=true
              - --entryPoints.websecure.address=:8443
              - --metrics.prometheus=true
              - --entrypoints.postgresql=true
              - --entryPoints.postgresql.address=:5432
              - --serverstransport.insecureskipverify=true

```
### Output of `traefik version`: 
```
traefik:v2.4.0
```

### PR DESCRIPTION
**Pull request by tomMoulard**
### What does this PR do?

Update the doc as the default value for `CheckNewVersion` is `true`: 
https://github.com/traefik/traefik/blob/438eec720a01476d2af699272d7fc3a22cb9356d/cmd/configuration.go#L22

### More

~~- [ ] Added/updated tests~~
- [X] Added/updated documentation

### Additional Notes

Fixes #7878

### CODE REVIEW

**Review by ldez — APPROVED** [review]
LGTM

**Review by mmatur — APPROVED** [review]
LGTM

**Review by rtribotte — APPROVED** [review]
LGTM 👌

**Review by kevinpollet — APPROVED** [review]
LGTM

**Pull request merged**
