### PR TITLE
Discrepancy in Traefik log levels

### PR DESCRIPTION
**Pull request by Nowheresly**
### What does this PR do?

This PR fixes issue #7722 .

### Motivation

The current logs for customerrors middleware generates too much non relevant error logs.
By decreasing the log level, traefik is now more cohesive in its log level.

### CODE REVIEW

**Review by jbdoumenjou — APPROVED** [review]
LGTM :+1:

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by jspdown — APPROVED** [review]
Thanks for your contribution @Nowheresly :+1:

**Comment by Nowheresly** [comment]
That was quick. Thanks to all the traefik maintainers!!

**Pull request merged**
