### PR TITLE
server: updating go-proxyproto with security bugfix from upstream

### PR DESCRIPTION
**Pull request by mschneider82**
security bug described in issue:

https://github.com/pires/go-proxyproto/issues/69

this affects traefik 2.4 with enabled proxy protocol support

https://github.com/pires/go-proxyproto/compare/v0.3.1...v0.5.0

### CODE REVIEW

**Comment by rtribotte** [comment]
Hello @mschneider82,

Thank you very much for this contribution.

Since it's a security/bug fix, it must be merged into the v2.4. Can you rebase your PR on the v2.4 branch?

**Comment by mschneider82** [comment]
ok should be fine now

**Comment by rtribotte** [comment]
Thank you 👍 
For now, we will wait for a proper tag. The update to go1.16 shouldn't be an issue, and at most, we will have to wait to merge the update on go1.16 Traefik PR #7932.

**Comment by mschneider82** [comment]
It's not required to wait until traefik upgrades to 1.16 (no dependency on upstream), I requested a tag from upstream maintainer

**Comment by mschneider82** [comment]
@rtribotte  updated to proper tag

**Comment by rtribotte** [comment]
@mschneider82 Thank you, I'll remove the no merge label

**Review by dtomcej — APPROVED** [review]
LGTM
:shipit:

**Review by ldez — APPROVED** [review]
LGTM

**Review by jbdoumenjou — APPROVED** [review]
LGTM :+1:

**Pull request merged**
