### PR TITLE
fix: IPv6 addr in square brackets

### PR DESCRIPTION
**Pull request by moonlightwatch**
### What does this PR do?

Fix the function `parseHost` got different result from the host `[ipv6Address]` and the host `[ipv6Address]:8000`

### Motivation

I have set the entryPoint on the port 80. And a router rule set as `Host(`ipv6address`)`.  
Send a request by curl : `curl http://[ipv6address]/`，I found the `RequestDecorator` parse the host to `[ipv6address]`. 
I try to set the port to 8080, and do `curl http://[ipv6address]:8080/`.  The `RequestDecorator` parse the host to `ipv6address`.

### More

- [x] updated tests
- [ ] ~updated documentation~

### CODE REVIEW

**Comment by ldez** [comment]
hello, can you prefer `rebase` over `merge` when you want to update your PR?

FYI, the PRs are automatically squashed and rebased when we merge a PR, you just have to rebase if your PR has conflicts.

**Comment by ldez** [comment]
You have missed something, I will clean your PR.
Screenshot 2022-09-08 at 12-48-24 Fix_ipv6 addr in square brackets by moonlightwatch · Pull Request #9313 · traefik_traefik

**Comment by moonlightwatch** [comment]
Thank you. I will do better next time.

**Review by rtribotte — APPROVED** [review]
Thanks 👍

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
