### PR TITLE
Add a link to service on router detail view

### PR DESCRIPTION
**Pull request by Tchoupinax**
### What does this PR do?

This PR adds the way to go to a service displayed in the router view detail by a click

### Motivation

I used a lot Traefik to have an overview of my router and my service and ensure all is correct when I am doing my configuration. However, I cannot go to the service from the router detail view, I have to click on "services" tab, search my service (among 30, for the moment...) and click again. I add the link and it works perfectly!

### Additional Notes

I did the feature the more simple way I could find and the most soft. I am opened to every suggestions or changes to respect the code's guidelines of the project :)

Thank for your work! ❤️

### CODE REVIEW

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by rtribotte — APPROVED** [review]
Thanks 👍

**Comment by Tchoupinax** [comment]
You are welcome :)

**Review by tomMoulard — APPROVED** [review]
LGTM :ok_hand:

**Pull request merged**
