### PR TITLE
Implement customizable minimum body size for compress middleware

### LINKED ISSUE #8197: Compress middleware: add option to configure the minimum body size
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

A configurable option to configure the minimum body size for the [compress middleware](https://doc.traefik.io/traefik/middlewares/compress/). 

For example: 
```
[http.middlewares]
  [http.middlewares.test-compress.compress]
    minimumBodySizeBytes = 5000
```

### PR DESCRIPTION
**Pull request by lus**
### What does this PR do?

This pull request aims to implement a way to customize the minimum body size for the [compress middleware](https://doc.traefik.io/traefik/middlewares/compress/) to apply.

According to the documentation, this minimum size should currently be hardcoded to **1400 bytes**, however, after some skimming through the code, I cannot find the part where that happens. Is this an issue in the documentation or is it an issue on my side?

### Motivation

1. I wanted to get into contributing to other, bigger projects and I really like traefik, so I chose to give it a try.
2. This feature was requested (#8197)

Fixes #8197

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

I would be happy about any constructive criticism as this is my first PR to traefik.
I may make some mistakes, like forgetting to change something in another area, because I don't know the complete codebase yet.

### CODE REVIEW

**Comment by dtomcej** [comment]
Hello @lus,

The default minimum size is defined here: https://github.com/traefik/gziphandler/blob/master/gzip.go#L36

and then used here: https://github.com/traefik/traefik/blob/master/pkg/middlewares/compress/compress.go#L67

**Comment by lus** [comment]
Alright, that makes sense.
Thank you very much :D

**Comment by lus** [comment]
Semaphore notes an error that I don't really know how to fix.
It looks like it is something about the references in the documentation?

**Comment by dtomcej** [comment]
Hello @lus,
Semaphore is breaking on label_test.go:1347, because the option was not added to the parse/decode test:

https://github.com/traefik/traefik/blob/master/pkg/config/label/label_test.go#L128

**Comment by lus** [comment]
Alright, thank you for helping me out!
Sorry again for my (sometimes dumb) mistakes.
I double-checked the tests locally again and everything should work out fine now.

**Review by kevinpollet — APPROVED** [review]
Hello @lus,

Nothing special to say regarding your contribution which was pretty good. We have only renamed the config option to `minResponseBodyBytes` to be consistent with the existing configuration options of the buffering [middleware](https://doc.traefik.io/traefik/middlewares/http/buffering/#configuration-options).

Thanks again for your contribution 🎉

**Review by rtribotte — APPROVED** [review]
Thanks 👍

**Review by jbdoumenjou — APPROVED** [review]
LGTM :+1:

**Pull request merged**
