### PR TITLE
Add jspdown to maintainers

### PR DESCRIPTION
**Pull request by emilevauge**
### What does this PR do?

This PR adds Harold Ozouf [jspdown](https://github.com/jspdown) to the maintainers team.

### Motivation

Harold is recognized for outstanding and valiant actions carried out lately.

### More

- [x] Added/updated documentation

### Additional Notes

image

### CODE REVIEW

**Review by ldez — APPROVED** [review]
:crossed_swords:

**Review by rtribotte — APPROVED** [review]
LGTM 🎉

**Review by nmengin — APPROVED** [review]
LGTM :crossed_swords:

**Review by jbdoumenjou — APPROVED** [review]
LGTM :confetti_ball:

**Review by kevinpollet — APPROVED** [review]
⚔️

**Review by dtomcej — APPROVED** [review]
LGTM
⚔️

**Pull request merged**
