### PR TITLE
Fix typos in migration guide 

### PR DESCRIPTION
**Pull request by marsavela**
### What does this PR do?

This changes adds a couple of missing quotations in the YAML section of the v1-to-v2.md file.

### Motivation

I've lost 10 minutes of my time debugging this. I don't want others to suffer as I did.

### More

- [x] Updated documentation

### CODE REVIEW

**Review by jbdoumenjou — APPROVED** [review]
LGTM :+1:

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by jspdown — APPROVED** [review]
LGTM :+1:

**Review by SantoDE — APPROVED** [review]
LGTM 👼 

Thanks!

**Pull request merged**
