### PR TITLE
Add a horizontal scroll for the mobile view

### LINKED ISSUE #10476: Add an ability to navigate on a dashboard from mobile device
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

As a Mobile Device User I want to be able to navigate on a webui dashboard.

**Motivation**: There is a pretty adaptive layout on a dashboard. But user cannot navigate between Dashboard / HTTP / TCP / UDP / Plugins dashboard menu. The same issue is with the HTTP Routers / HTTP Services / HTTP Middlewares sub-menu items.

### PR DESCRIPTION
**Pull request by framebassman**
### What does this PR do?
Closes #10476

Before:
image

After:
image

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by framebassman** [comment]
It can close https://github.com/traefik/traefik/issues/10476 #10476

**Comment by rtribotte** [comment]
Hello @framebassman,

Thanks for opening this!

I tried the changes and I can see that the "upgrade" tooltip is now broken:

Capture d’écran 2024-03-05 à 10 52 43

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by youkoulayley — APPROVED** [review]

**Comment by framebassman** [comment]
@kevinpollet there is no diff between this PR and v2.11 version. Could we close this PR without merge?

**Comment by kevinpollet** [comment]
Hello @framebassman, I am closing this pull request as there are no changes, please open a new pull request.

**Comment by ldez** [comment]
the problem is just a wrong merge, no need for a new PR.

**Comment by framebassman** [comment]
@kevinpollet Seems my changes are already delivered into v2.11 branch - 1a266c661aa5e6f0baba8b091fa4533289c48f44
Thank you all guys for your time.

**Comment by ldez** [comment]
In fact, the change was already inside another PR.

**Comment by ldez** [comment]
There is an error during the merge of the PR, it's weird.

**Comment by framebassman** [comment]
@ldez should we close the https://github.com/traefik/traefik/issues/10476 cause the changes is delivered?

**Pull request closed without merging**
