### PR TITLE
Update proxy.go

### PR DESCRIPTION
**Pull request by wangfeng22**
I think that this code can be deleted.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by kevinpollet** [comment]
Please open an issue or at least fill up the motivation to explain the goal of this PR.

**Comment by wangfeng22** [comment]
> Please open an issue or at least fill up the motivation to explain the goal of this PR.

ok thanks. how about this?

**Comment by kevinpollet** [comment]
Why do you think that those lines are redundant?

Maybe you missed that the websocket headers case are not the same (e.g. Sec-Web**S**ocket-Key is not the same as Sec-Web**s**ocket-Key).

**Comment by wangfeng22** [comment]
> Why do you think that those lines are redundant?
> 
> Maybe you missed that the websocket headers case are not the same (e.g. Sec-Web**S**ocket-Key is not the same as Sec-Web**s**ocket-Key).

ohh, yes, thank you for your reminder

**Pull request closed without merging**
