### PR TITLE
Add support Knative by kubernetes crd. tested on 0.16.0 + k8s 1.18.3

### PR DESCRIPTION
**Pull request by ZCube**
### What does this PR do?

Traefik as Knative Ingress #5081

### Motivation

I wanted to use traefik as the only ingress.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Tested on Knative 0.10 + Kubernetes 1.14

#### Test
1. Install Knative

```
kubectl apply  --selector knative.dev/crd-install=true \
   --filename https://github.com/knative/serving/releases/download/v0.9.0/serving.yaml \
   --filename https://github.com/knative/eventing/releases/download/v0.9.0/release.yaml

kubectl apply --filename https://github.com/knative/serving/releases/download/v0.9.0/serving.yaml \
   --filename https://github.com/knative/eventing/releases/download/v0.9.0/release.yaml
```

2. Install Treafik

from https://github.com/containous/traefik-helm-chart
add ClusterRole
```
  - apiGroups:
      - networking.internal.knative.dev
    resources:
      - ingresses
      - serverlessservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.internal.knative.dev
    resources:
      - ingresses
      - clusteringresses
      - ingresses/status
      - clusteringresses/status
    verbs:
      - update
```

Create test service.
```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go
        env:
        - name: TARGET
          value: Go Sample v1
```

#### Results

curl 192.168.100.3/api/http/services
```
[
   {
      "loadBalancer":{
         "servers":[
            {
               "url":"http://10.99.135.193:80"
            }
         ],
         "passHostHeader":true
      },
      "status":"enabled",
      "usedBy":[
         "default-helloworld-go-57xxt@kubernetescrd"
      ],
      "serverStatus":{
         "http://10.99.135.193:80":"UP"
      },
      "name":"default-helloworld-go-57xxt@kubernetescrd",
      "provider":"kubernetescrd",
      "type":"loadbalancer"
   }
]
```

curl 192.168.100.3/api/http/routers
```
[
   {
      "middlewares":[
         "helloworld-go-Retry@kubernetescrd",
         "default-helloworld-go-57xxt-AppendHeader@kubernetescrd"
      ],
      "service":"default-helloworld-go-57xxt",
      "rule":"(Host(`helloworld-go.default.svc.cluster.local`) || Host(`helloworld-go.default.example.com`))",
      "status":"enabled",
      "using":[
         "traefik",
         "web",
         "websecure"
      ],
      "name":"default-helloworld-go-57xxt@kubernetescrd",
      "provider":"kubernetescrd"
   }
]
```

curl 192.168.100.3/api/http/middlewares
```
[
   {
      "headers":{
         "customRequestHeaders":{
            "Knative-Serving-Namespace":"default",
            "Knative-Serving-Revision":"helloworld-go-57xxt"
         }
      },
      "status":"enabled",
      "usedBy":[
         "default-helloworld-go-57xxt@kubernetescrd"
      ],
      "name":"default-helloworld-go-57xxt-AppendHeader@kubernetescrd",
      "provider":"kubernetescrd",
      "type":"headers"
   },
   {
      "retry":{
         "attempts":3
      },
      "status":"enabled",
      "usedBy":[
         "default-helloworld-go-57xxt@kubernetescrd"
      ],
      "name":"helloworld-go-Retry@kubernetescrd",
      "provider":"kubernetescrd",
      "type":"retry"
   }
]
```

### CODE REVIEW

**Comment by dtomcej** [comment]
Hello @ZCube,

We apologize for the large delay on responding to this PR.

We have been keeping an eye on the Knative ecosystem to see how it evolved over time, to see if it was something that we were interested in.

Being that sufficient time has passed, we are currently in the process of re-evaluating the Knative sphere, and the feasibility of supporting it in Traefik.

We should have a follow up for you shortly.

Thanks again,

The Traefik Team

**Comment by SantoDE** [comment]
Hello @ZCube,

thanks for your contribution to the Project. Sorry for taking some time to look at it, but now we're here.

After looking at your project, we see that you kinda implemented that functionality in the k8s CRD provider. While it has its advantages in re-using code, it's not what we would require.

For us, it knative serving should be its own provider rather than the CRD provider for example. Do you have some time to upgrade that PR? Also, as you probably know, Knative serving is currently in 0.14 and this is tested against 0.9. 

Could you upgrade the PR to work with knative serving 0.14?

Thanks.

**Comment by ZCube** [comment]
Hello.

I am currently using this personally. There was no problem with this version for me to use.

(kubernetes v1.18.3,
knative v0.14)

Featuers added between v0.9 and v0.14 are not checked.

I think you want to clone the provider. The reasons for modifying the provider without cloning it.

1. I tried to make it easy to understand by minimizing the modification.

2. I tried not to make duplicate code possible.

3. I didn't know where and how to start adding providers.

4. I was weak in English and wanted to avoid the development of adding documents.

Thanks. (With Google Translator)

**Comment by SantoDE** [comment]
Hello @ZCube,

sorry for the late replay.

Thanks for splitting it into a separate provider. There's still documentation missing, can you please provide it? Afterwards we can take a proper review.

**Comment by SantoDE** [comment]
Hello @ZCube,

sorry for the late replay.

Thanks for splitting it into a separate provider. There's still documentation missing, can you please provide it? Afterwards we can take a proper review.

**Comment by ZCube** [comment]
@SantoDE 
There is still more work to be done, but progress is slow because I need to study more about crd. It seems to take some time to review.

**Comment by SantoDE** [comment]
Thank you @ZCube,

there is also no tests yet. Will you add those? :)

**Comment by pyramation** [comment]
watching, happy to see this :)

**Comment by ZCube** [comment]
@SantoDE 

I am busy lately. So, I simply share my testing environments. Just working version.
* Using MetalLB LoadBalancer (192.168.100.3, 192.168.100.4)
* Knative 0.16
* k8s v1.18.3

```
# build docker image and load to test node (You have to build it yourself. https://github.com/ZCube/traefik, knative-ingress branch)
make build-image 
# install knative 0.16.0
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.16.0/serving-crds.yaml
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.16.0/serving-core.yaml
# install traefik2
kubectl patch configmap/config-network \
  --namespace knative-serving \
  --type merge \
  --patch '{"data":{"ingress.class":"traefik.ingress.networking.knative.dev"}}'
kubectl apply -n kube-system -f traefik2.yml
# deploy go-hello
kubectl apply -f knative-test-v1.yml
```

knative-test-v1.yml
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go2
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go
        env:
        - name: TARGET
          value: Go Sample v1
```

traefik2.yml
```
---
# Source: traefik/templates/rbac/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik2

---
# Source: traefik/templates/rbac/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik2
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - ingressroutetcps
      - middlewares
      - tlsoptions
    verbs:
      - get
      - list
      - watch
  - apiGroups: 
      - networking.internal.knative.dev
    resources: 
      - ingresses
      - serverlessservices
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - networking.internal.knative.dev
    resources: 
      - ingresses
      - clusteringresses
      - ingresses/status
      - clusteringresses/status
    verbs:
      - update

---
# Source: traefik/templates/rbac/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik2
subjects:
- kind: ServiceAccount
  name: traefik2
  namespace: kube-system

---
# Source: traefik/templates/dashboard-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik2-dashboard
  labels:
    #networking.knative.dev/ingress-provider: traefik 
    app: traefik
    chart: "traefik-2.0.0"
    release: "traefik2"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.4
  selector:
    app: traefik
    release: traefik2
  ports:
  - port: 80
    name: traefik
    targetPort: traefik

---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik2
  labels:
    networking.knative.dev/ingress-provider: traefik 
    app: traefik
    chart: "traefik-2.0.0"
    release: "traefik2"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.3
  #externalTrafficPolicy: Local
  selector:
    app: traefik
    release: traefik2
  ports:
  - port: 80
    name: web
    targetPort: web
  - port: 443
    name: websecure
    targetPort: websecure

---
# Source: traefik/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik2
  labels:
    app: traefik
    chart: traefik-2.0.0
    release: "traefik2"
    heritage: "Tiller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
      release: traefik2
  template:
    metadata:
      labels:
        app: traefik
        chart: traefik-2.0.0
        release: "traefik2"
        heritage: "Tiller"
    spec:
      serviceAccountName: traefik2
      terminationGracePeriodSeconds: 60
      containers:
      - image: containous/traefik:latest
        imagePullPolicy: Never
        name: traefik2
        resources:
          limits:
            cpu: 300m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
          
        readinessProbe:
          httpGet:
            path: /ping
            port: 9000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: 9000
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - name: web
          containerPort: 8000
          protocol: TCP
        - name: websecure
          containerPort: 8443
          protocol: TCP
        - name: traefik
          containerPort: 9000
          protocol: TCP
        args:
          - "--entryPoints.web.address=:8000"
          - "--entryPoints.websecure.address=:8443"
          - "--entryPoints.traefik.address=:9000"
          - "--api.dashboard=true"
          - "--api.insecure=true"
          - "--ping=true"
          - "--providers.knative"
          - "--providers.knative.loadBalancerIP=192.168.100.4"
          - "--log.level=INFO"
```

**Comment by ZCube** [comment]
image

**Comment by jansauer** [comment]
@ZCube Works perfectly. Have tested it with the latest knative version. What was your reason for keeping the prefix for the names in traefik. Why not use <namespace>-<app>? This would allow using the Services with other custom routes.

@SantoDE is it only tests and docs that would need to be added? I could help with the docs but golang os not my home turf. I tried understanding the other kubernetes tests but so far i don't think that my work would be good enough.
I don't even get why separating the code from the other kubernetes related providers should be a good idea.

**Comment by SantoDE** [comment]
Hey @jansauer,

test& docs are still missing, yeah. 

The provider is alreay split out in its own, so thats a good thing.

To me, it would be a great help if you could test this integration with the current knative versions as this PR is a little old and I dont know how well it aged. How does that sound?

**Comment by jansauer** [comment]
@SantoDE sounds like something i can do :-) 
My test setup is already running the latest version but i will do some more tests in the next days.

**Comment by info4vincent** [comment]
I am running k3os with Traefik. I would like to use Knative together with the Traefik ingress controller. So found this pull request. What is the latest status?

**Comment by ddtmachado** [comment]
Hello everyone, 

We still view this as a nice enhancement to have, but since the PR is a few years old already and there has been no activity from the contributors lately I'm going to close it as working to update it is a good amount of work now (Kubernetes libraries and Traefik code changes) plus it still lacks integrated tests and documentation.

Having said that, if anyone on the community would like to take over and do the work opening a new PR that's ready to be reviewed we would be more than happy :)

**Pull request closed without merging**
