### PR TITLE
Add missing doc about servers transport.

### PR DESCRIPTION
**Pull request by ldez**
### What does this PR do?

Add missing doc about servers transport.

### Motivation

Have better documentation.

### More

- ~~[ ] Added/updated tests~~
- [x] Added/updated documentation

### CODE REVIEW

**Review by mmatur — APPROVED** [review]
LGTM

**Review by juliens — APPROVED** [review]
LGTM

**Review by rtribotte — APPROVED** [review]
LGTM 👌

**Review by kevinpollet — APPROVED** [review]
LGTM

**Pull request merged**
