### PR TITLE
Allow createPluginMiddleware load value from secret

### LINKED ISSUE #8994: Plugin has no option to read config from k8s secret file.
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I made some custom plugins and some of them need to read secret from k8s secret file. Such as JWT, verify signature should be in the k8s secret, and middleware spec config should read from it.

### PR DESCRIPTION
**Pull request by longquan0104**
### What does this PR do?

This PR allow plugin middleware read config from k8s secret file.
This modifies the function createPluginMiddleware.
When run this function it will check if any config have this urn format: `urn:k8s:secret:namespace:secretName:secretKey`

### Motivation

When write a custom plugin such as jwt, some needed to be in the secret not to be exposed.

Fixes #8994
Related to #8991

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by longquan0104** [comment]
Hi @ldez 
Please have a look at this. Thank you 😶😶😶

**Comment by kevinpollet** [comment]
Hello @longquan0104,
 
Thanks for your contribution,

This PR is labeled as `needs-design-review`, as you can see in our [contribution guide](https://github.com/traefik/contributors-guide/blob/master/review_guidelines.md), this means that we have to take a longer look to evaluate how it would interact with the other parts of Traefik.

We will come back to you once the design review iteration is done.

**Comment by longquan0104** [comment]
Hello @kevinpollet,

I'm looking forward to hearing any updates from the Traefik team.

Thank you.

**Comment by rtribotte** [comment]
Superseded by #9103.

**Comment by longquan0104** [comment]
Sorry that I missed your comment about opening a new PR. 
Found #9103. Please merge it if it is okay and works well. Thank you for your help.

**Pull request closed without merging**
