### PR TITLE
Add access log filter for excluded URLs

### PR DESCRIPTION
**Pull request by hakman**
### What does this PR do?

This change allows users to add access log filters based on URLs.

### Motivation

This would allow to:
1. not log access to sensitive resources, when privacy is a requirement
2. not log health checks and other annoyances

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

Fixes: #6861

### CODE REVIEW

**Comment by kevinpollet** [comment]
Hello @hakman,
 
Thanks for your interest in Traefik,

This PR is labeled as `needs-design-review`,
as you can see in our [contribution guide](https://github.com/traefik/contributors-guide/blob/master/review_guidelines.md), this means that we have to take a longer look to evaluate how it would interact with the other parts of Traefik.

We will come back to you once the design review iteration is done.

**Comment by hakman** [comment]
Thanks for the feedback @kevinpollet. Looking forward to the review. 😄

**Comment by kevinpollet** [comment]
Hello @hakman,

Thanks for your contribution,

We reviewed your pull request, and unfortunately, we are declining it. Adding an `excludedURLsRegex` option will negatively impact the performances, as this `regex` needs to be evaluated for each HTTP request.

We think that a better approach would be to always disable the access logs for the ping router or leverage the log aggregation tool to filter out unwanted entries/URLs.

**Comment by Dirrk** [comment]
@kevinpollet would a static string match also not be acceptable? ie: 
```
excludedPaths:
      - /ping
      - /metrics
```

**Comment by kevinpollet** [comment]
Hi @Dirrk,

This would have an impact on performances (certainly less) but this check will have to be done for each request, and for sure one would want regex at some point. So, we still think that a better approach would be to always disable the access logs for the ping router or leverage the log aggregation tool to filter out unwanted entries/URLs.

**Comment by obourdon** [comment]
Hi @kevinpollet could you please give some hints on how to achieve disabling of access logs for the ping router. I was unable to find anything easily in the docs for that matter. Many thanks

**Comment by obourdon** [comment]
IMHO I am more for letting people have access to this kind of feature with indeed a big warning on performances. I can think of several other products/technologies which had to implement similar requests with very similar impacts but almost all of them agreed to let those in.

**Comment by obourdon** [comment]
@kevinpollet (or anyone else) any comments on what I wrote above please ?

**Comment by mpl** [comment]
> Hi @kevinpollet could you please give some hints on how to achieve disabling of access logs for the ping router? I was unable to find anything easily in the docs for that matter. Many thanks

Just to clarify as of now this cannot be done just with configuration. Kevin was talking about how we could/should do it to actually fix the problem with code in Traefik.

**Comment by ngbrown** [comment]
I see that this was declined because of regex. If it was exact match instead of regex, would that be acceptable? I see this configurable approach may be preferable over disabling on the ping router because an application may need to be regularly pinged through the traefik gateway.

**Comment by changhyuni** [comment]
If Regex performance is an issue, why not implement substring?

**Comment by zawadaa** [comment]
IMO for 99% of users enough will be one flag:
log or not *@internal

**Pull request closed without merging**
