### PR TITLE
[WIP] Configure DNSChallenge provider using environment variables passed through config.

### PR DESCRIPTION
**Pull request by IlyaGulya**
### What does this PR do?

Adds the ability to apply multiple configurations to DNS challenge providers.
It allows passing specific environment variables during the creation of the DNS challenge provider.

Those variables are placed under `certificatesResolvers.<name>.acme.dnsChallenge.environment`

Example:
```
[certificatesResolvers.CertificateResolver1.acme.dnsChallenge.environment]
  foobar = "foobar"
```
Environment variable `foobar` with the value `foobar` will be passed to the DNS challenge provider during its creation.

This is done by overriding environment variables during provider creation and restoring the previous environment status after it.

### Motivation

I wanted the ability to pass different configurations to different providers because I own several domains and my DNS provider generates different API keys for different domains.
Also, there's an issue that is not resolved yet: https://github.com/traefik/traefik/issues/5472

### More

- [x] Added tests for dns challenge provider configuration
- [x] Updated documentation

### Additional Notes

I'm completely aware that this implementation is quite hacky.
The right solution will require huge PR to https://github.com/go-acme/lego for it to support configuration through code.

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

As explained here https://github.com/traefik/traefik/issues/5472#issuecomment-534908109, this approach will not really work.

And there is a concurrency issue.

I already declined PRs with this kind of approach in lego.

So we will decline.

**Comment by IlyaGulya** [comment]
> Hello,
> 
> As explained here [#5472 (comment)](https://github.com/traefik/traefik/issues/5472#issuecomment-534908109), this approach will not really work.
> 
> And there is a concurrency issue.
> 
> I already declined PRs with this kind of approach in lego.
> 
> So we will decline.

According to my small research, every single DNS provider in `lego` currently uses environment variables to configure itself.
So, this approach does really work. And it works for each of supported providers in `lego`.

Until there no other ways to configure providers in `lego`, I think this is not that bad way to fix this issue.

**Comment by ldez** [comment]
I'm the main maintainer of lego, according to my knowledge, every single DNS provider doesn't use env vars, sorry.

**Comment by IlyaGulya** [comment]
> I'm the main maintainer of lego, according to my knowledge which is exhaustive, every single DNS provider doesn't use env vars, sorry.

Ok.
I've looked over every provider before writing previous message and haven't seen any which can't be configured using env vars :smile: 
Maybe I've missed one or two, my fault. (you could have pointed on one of them for this conversation to be more productive, btw)

Nevertheless, my approach adds a configuration entry called `environment`.
I think it's quite obvious for consumers that this feature allows to configure only those DNS providers which can be configured using environment variables.

What's wrong with ability to solve several users' issue?
This change does not seem to impact on any other traefik subsystems.
It's very easy and clear.
It would be easy to remove once proper solution will be implemented.

Current situation involves a lot of unneeded complexity for cases which does not require it.

**Pull request closed without merging**
