### PR TITLE
Advanced modify HTTP header

### PR DESCRIPTION
**Pull request by incubator4**
### What does this PR do?

1. Implement new method to modify http header with Add/Replace/Delete
2. Delete Header function support remove specific k/v instead of all.

### Motivation

I saw the issue #9471, and I  would love to Implement it for community.

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### CODE REVIEW

**Comment by tfny** [comment]
Hey @incubator4, I wanted to let you know that the team has seen this and is currently discussing the proposal.  

When the team is done verifying the use-case we will move it to design review.  At that point, we will get back to you with any questions or concerns about obvious conflicts with the current codebase before moving to code review.

**Comment by incubator4** [comment]
> Hey @incubator4, I wanted to let you know that the team has seen this and is currently discussing the proposal.
> 
> When the team is done verifying the use-case we will move it to design review. At that point, we will get back to you with any questions or concerns about obvious conflicts with the current codebase before moving to code review.

I'm glad to hear about that, I'd love to continue this PR after discussion.

**Comment by incubator4** [comment]
@rtribotte  I've already done new PR, please review.

**Comment by mpl** [comment]
> @rtribotte I've already done new PR, please review.

Hello @incubator4 ,

Is this new version supposed to be the full implementation for the plan we proposed? Or do you have more commits incoming soon? Or are you proposing to split the plan we proposed into several PRs?

We are asking, because we had a look and it does not seem that this implementation fully corresponds to what we proposed.

Notably:

1) CustomRequestHeaders and CustomResponseHeaders should have been removed
2) RequestHeaders and ResponseHeaders should be the only ones left in the Headers type. All the other fields/options (from `AccessControlAllowCredentials` to `IsDevelopment`) should be moved to a new middleware, so they should become the fields of a new 
```
type SecurityHeaders struct {
...
}
```
 
 WDYT? Do you have any question?

**Comment by incubator4** [comment]
> > @rtribotte I've already done new PR, please review.
> 
> Hello @incubator4 ,
> 
> Is this new version supposed to be the full implementation for the plan we proposed? Or do you have more commits incoming soon? Or are you proposing to split the plan we proposed into several PRs?
> 
> We are asking, because we had a look and it does not seem that this implementation fully corresponds to what we proposed.
> 
> Notably:
> 
> 1. CustomRequestHeaders and CustomResponseHeaders should have been removed
> 2. RequestHeaders and ResponseHeaders should be the only ones left in the Headers type. All the other fields/options (from `AccessControlAllowCredentials` to `IsDevelopment`) should be moved to a new middleware, so they should become the fields of a new
> 
> ```
> type SecurityHeaders struct {
> ...
> }
> ```
> 
> WDYT? Do you have any question?

My apologize, I'd continue it.

**Comment by incubator4** [comment]
@mpl would you mind review that again in soon later, I've saw any one focus on this PR

**Comment by mpl** [comment]
> @mpl would you mind review that again in soon later, I've saw any one focus on this PR

Hello @incubator4 ,

FYI, we haven't forgotten about you, but it might take a while before we can come back to you, sorry.

**Comment by rtribotte** [comment]
Hello @incubator4,

Considering the new strategy plan for v3 (see this [comment](https://github.com/traefik/traefik/issues/10260#issuecomment-1867474446)), the changes in this PR would no longer fit for v3, as they would be breaking.
As one possible alternative, we could introduce a specific (hidden?) header middleware to support fully the HTTPRouteFilter.

For now, it seems preferable to decline and close this pull request, but we are looking forward to working with you on this if you are willing to.

**Pull request closed without merging**
