### PR TITLE
Support InfluxDB v2 metrics backend

### LINKED ISSUE #6389: [metrics] InfluxDB v2 support
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

For instance `traefik` can send metrics to `InfluxDB 1.x`. Their new version is available as beta.
It could be nice to support a v2 endpoint and avoid using `telegraf` and their `InfluxDB v1` listener as a proxy to `InfluxDB v2`.

### PR DESCRIPTION
**Pull request by sh7dm**
### What does this PR do?
Support InfluxDB v2 as a backend for exporting metrics.

### Motivation
Fixes #6389

### More
TODO:
- [x] Add tests
- [x] Add documentation page for InfluxDB 2

### CODE REVIEW

**Comment by Xstoudi** [comment]
Any update on this one? How can we help?

**Comment by kevinpollet** [comment]
Hello,

As you can see in our [contribution guide](https://github.com/traefik/contributors-guide/blob/master/review_guidelines.md), `needs-design-review` means that we have to take a closer look at the scope of impact for that PR to see, how it would interact with the other parts of Traefik.

We will come back to you soon when we did the first design review iteration.

**Comment by sh7dm** [comment]
What's the progress on review? Does the branch need to be rebased/conflicts resolved?

**Comment by fdelucchijr** [comment]
Any update? 🤔😯

**Comment by sh7dm** [comment]
Great, thank you for resolving merge conflicts! Review comments are welcome

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by rtribotte — APPROVED** [review]
Thanks 👍

**Comment by fdelucchijr** [comment]
Thanks!!

**Comment by albertosgz** [comment]
Great job guys!! This commit is very helpful for our purposes.
However, I cannot see this enhacement in the last release available 2.6.1, is planned to let it available soon? 
I am running traefik trhough docker.

**Comment by kevinpollet** [comment]
Hello @albertosgz,

As the support of InfluxDB v2 is an enhancement, it will be available in the next minor release of Traefik, which should be `v2.7.0`.

**Comment by giodamelio** [comment]
For impatient people like me, I was able to get it working with the likely totally not supported `docker.io/traefik/traefik:experimental-master` image (built by this [Github Action](https://github.com/traefik/traefik/actions/workflows/experimental.yaml))

My config looks like this:

```toml
[metrics]
  [metrics.influxDB2]
  address = "<address_with_port>"
  token = "<token>"
  org = "homelab"
  bucket = "default"
```

**Comment by ser** [comment]
> For impatient people like me, I was able to get it working with the likely totally not supported `docker.io/traefik/traefik:experimental-master` image (built by this [Github Action](https://github.com/traefik/traefik/actions/workflows/experimental.yaml))
> 
> My config looks like this:
> 
> ```toml
> [metrics]
>   [metrics.influxDB2]
>   address = "<address_with_port>"
>   token = "<token>"
>   org = "homelab"
>   bucket = "default"
> ```

What if there are several traefik instances, how do we distinguish them?

**Comment by sh7dm** [comment]
You can configure the bucket used in config for InfluxDB 2.0 provider. Use different buckets for each Traefik instance, then find data in the buckets you need.

**Comment by ser** [comment]
What if I want to use one bucket only?

**Comment by sh7dm** [comment]
Then I guess there is no simple way, because buckets (and orgs as well) are created to separate same data values from different sources.

**Comment by ser** [comment]
OK that's sad, multiple buckets complicate access, so I will stay with telegraf/prometheus gateway then

**Comment by sh7dm** [comment]
Consider consulting experts in InfluxDB or official docs, I do not have proficiency with it.

**Comment by ser** [comment]
My expert in InfluxDB suggests that a `host` parameter in traefik would be a solution:
```
[metrics]
  [metrics.influxDB2]
  address = "<address_with_port>"
  token = "<token>"
  org = "homelab"
  bucket = "default"
  host = "traefik1ofMany"
```

**Comment by kevinpollet** [comment]
Hello,

As explained in the documentation: https://doc.traefik.io/traefik/v2.7/observability/metrics/influxdb2/#additionallabels, the `additionalLabels` option can be leveraged to achieve that.

**Pull request merged**
