### PR TITLE
Add ResponseCode to CircuitBreaker's k8s CRD

### PR DESCRIPTION
**Pull request by fahhem**
### What does this PR do?

Follow up from https://github.com/traefik/traefik/pull/10147 to update the CRDs for k8s.

### Motivation

I updated to the latest traefik to use the new features, but then found out my middleware was failing validation.

### More

- [x] Added/updated tests (N/A)
- [x] Added/updated documentation

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

can you run `make generate-crd` locally?

**Comment by ldez** [comment]
In fact, the problem is not here, I will open a PR to fix that.

**Comment by fahhem** [comment]
Yeah, I noticed it's pulling this from another file, I'm in the process of updating it but if you're done I'll stop. Thanks!

**Comment by ldez** [comment]
PTAL #10625

**Comment by ldez** [comment]
I close your PR as the other PR supersedes this one.

Thank you :+1:

**Pull request closed without merging**
