### PR TITLE
Add support HTTP/2 Server Push

### PR DESCRIPTION
**Pull request by janatjak**
### What does this PR do?

This MR add support for HTTP/2 Server Push

### Motivation

Access log and metrics wrap `http.ResponseWriter` and then it's not possible to use build-in Push feature in local middleware plugin (example https://github.com/janatjak/traefik-plugins/blob/master/http2push/http2push.go#L76)

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by valy23** [comment]
Hi,
I would like to support the merge of this code to Traefik.
ServerPush technology delivers measurable performance gains and is part of the HTTP/2 standard. It is supported by all browsers.

**Comment by jakubhonisek** [comment]
Great, thanks for fixing this issue. We also encountered this problem.

**Comment by kbogi** [comment]
When is the release scheduled?

**Comment by rtribotte** [comment]
Hello @janatjak,

Thank you for your contribution.

As mentioned in the closed PR #7308:

> In order to be able to comply with HTTP2 push, the support of the http.Pusher interface should be done in all needed places.
...
We also have in mind that is probable that the Chromium team will (remove the support for HTTP2 push), and we are looking forward to seeing their conclusion.

Unfortunately, for those same reasons, we are still not convinced that we have to add this feature to Traefik.

I will close this PR accordingly.

**Pull request closed without merging**
