### PR TITLE
Add s390x arch support

### LINKED ISSUE #8728: Add s390x arch support
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Can you add s390x support for Traefik? Is it planned ?

https://github.com/traefik/traefik-library-image/issues/20

PR - https://github.com/traefik/traefik/pull/8729

### PR DESCRIPTION
**Pull request by rohitsakala**
### What does this PR do?

Add s390x arch support 

### Motivation

Increasing usage of Kubernetes on s390x.

Fixes #8728

### CODE REVIEW

**Comment by rohitsakala** [comment]
@ldez Could you review this PR ? Thanks 😄

**Comment by rohitsakala** [comment]
@rodrigodiez @tomMoulard @rtribotte Could you review this ? or allow running of Github checks as a first step.

Thanks :smile:

**Comment by rohitsakala** [comment]
@ldez any update on this PR ?

**Comment by rohitsakala** [comment]
@ldez All checks have passed. Can we merge ? Thanks

**Review by tomMoulard — APPROVED** [review]
LGTM :ok_hand:

**Review by ldez — APPROVED** [review]
LGTM

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Pull request merged**
