### PR TITLE
fix(docs): header middleware examples

### PR DESCRIPTION
**Pull request by alexandre-abrioux**
I found some incoherences while reading the header middleware documentation.
Please let me know if I made a mistake! Thank you 🙂

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

can you rebase your PR on the v2.8 branch?

**Comment by alexandre-abrioux** [comment]
@ldez Thank you, it's done! FYI I clicked on the "edit" button in the documentation and it redirected me to the edition of the document in the master branch, this is why I ignored the template.
-> if you click "edit" on the experimental doc it asks to edit the master branch
-> if you click "edit" on the v2.8 doc it asks to edit the v2.8 branch

**Comment by rtribotte** [comment]
Hello @alexandre-abrioux,

The `customresponseheaders` [option](https://doc.traefik.io/traefik/middlewares/http/headers/#customresponseheaders) allows defining a custom set of headers to add to the response.
It is not a configuration node holding other options.

We will close this PR accordingly. Let us know if you think that we missed something.

**Comment by alexandre-abrioux** [comment]
Hi @rtribotte! Thank you for your answer: indeed, I got confused! My CORS middleware wasn't working and I thought there was an issue with the documentation. My issue was that I was using `headers.accesscontrolalloworigin` instead of `headers.accesscontrolalloworiginlist`. Sorry about the confusion 🙂

**Pull request closed without merging**
