### PR TITLE
Docker swarm DNSRR use DNS prefix "tasks." to target containers instead of unsupported

### PR DESCRIPTION
**Pull request by roman-vanicek**
### What does this PR do?

Use docker swarm DNS prefix "tasks." to target containers when the docker container endpoint uses DNSRR and Traefik has the LBSwarm flag enabled. 

### Motivation

Traefik should let docker do the loadbalancing as indicated by the LBSwarm flag. Currently such behavior is unsupported and causes a warning. Also discussed in #3288

### CODE REVIEW

**Comment by tfny** [comment]
Hey @roman-vanicek, would you mind providing a test case (Docker manifest) to allow us to better evaluate this?

**Comment by rtribotte** [comment]
Hello @roman-vanicek,

Sorry for the misunderstanding, what @tfny asked was not for a docker image, but a reproduction case with a docker-compose file that would help us to evaluate the PR changes.

**Comment by Rush** [comment]
Any updates on this PR @roman-vanicek ?

**Comment by nmengin** [comment]
Hey @Rush,

We are still interested in this feature but unfortunately, the tests are still missing.
I don't know if @roman-vanicek had planned to integrate them, but do not hesitate to contribute if you think you can provide such a test.

We'd like the community help on it.

**Comment by nmengin** [comment]
Hello,

This PR has been open for more than one year with no update on it despite the comment we left.
For this reason, we prefer to close it.

If you are interested in such a feature, please open a new PR.

**Pull request closed without merging**
