### PR TITLE
Allow to define datadogs metrics endpoint with env vars

### PR DESCRIPTION
**Pull request by sylr**
### What does this PR do?

Apply same env var mechanism used for datadog tracer endpoint for datadog metrics endpoint.

### Motivation

Ease configuration when using datadog on kubernetes.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Related to #7721

### CODE REVIEW

**Comment by rtribotte** [comment]
Hello @sylr,

Thanks for your contribution!

I wonder if the env variables are the right ones though. In [this page](https://docs.datadoghq.com/agent/docker/apm/?tab=linux) of the Datadog documentation it seems that would be:

> DD_HOSTNAME | Manually set the hostname to use for metrics if autodetection fails, or when running the Datadog Cluster Agent.
DD_DOGSTATSD_PORT | Set the DogStatsD port.

It seems that `DD_METRICS_AGENT_PORT` doesn't exist.

WDYT?

**Review by rtribotte — APPROVED** [review]
Thank you 👍

**Review by jbdoumenjou — APPROVED** [review]
LGTM :+1:

**Review by SantoDE — APPROVED** [review]
LGTM

**Pull request merged**
