### PR TITLE
Update to go1.16

### LINKED ISSUE #7920: go module support for traefik v1
v1 of this tool is installable via brew. in order to maintain go 1.17 support please consider porting go module support to v1 of this tool

Homebrew/homebrew-core#47627

### PR DESCRIPTION
**Pull request by ldez**
### What does this PR do?

Update to go1.16

### Motivation

Be able to get security fixes from Go and dependencies.

Fixes #7920

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Co-authored-by: Julien Salleyron <julien.salleyron@gmail.com>
Co-authored-by: Michael Matur <michael.matur@gmail.com>

### CODE REVIEW

**Review by rtribotte — APPROVED** [review]
LGTM 👌

**Review by jbdoumenjou — APPROVED** [review]
LGTM :zap:

**Review by juliens — APPROVED** [review]
LGTM

**Comment by ldez** [comment]
Sounds like a bug in Github or our bot, because the PR has been merged in c47849d43ab41c39648f301c85a8c12e963b2237

**Pull request closed without merging**
