### PR TITLE
UI unit tests vitest

### PR DESCRIPTION
**Pull request by framebassman**
### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

The web UI has been updated in v3.0, I'm not sure it is worth it to make changes on v2.11, and this can cause problems during merge back of v2.11 on v3.0

Maybe you can take a look at the v3.0 branch?

**Comment by framebassman** [comment]
Ok, I will take a look

**Comment by framebassman** [comment]
The PR for v3.0 - #10641

**Comment by framebassman** [comment]
Reopen this one in #10665

**Pull request closed without merging**
