### PR TITLE
Update sprig to v3.2.0

### PR DESCRIPTION
**Pull request by sirlatrom**
### What does this PR do?

Updates the version of the sprig library to v3.2.0 to include, among other things, the `fromJson, mustFromJson` functions.

### Motivation

I saw the `fromJson, mustFromJson` functions in sprig's documentation but could not use them in Traefik's dynamic configuration in the File provider.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

http://masterminds.github.io/sprig/defaults.html#fromjson-mustfromjson

### CODE REVIEW

**Comment by rtribotte** [comment]
Hello @sirlatrom,

Thanks for your contribution!

I'm wondering about potential regressions.
Since it's a major version change, can you provide a diff of something that would make clear that there is no expected regression?

**Comment by sirlatrom** [comment]
> Hello @sirlatrom,
> 
> Thanks for your contribution!
> 
> I'm wondering about potential regressions.
> Since it's a major version change, can you provide a diff of something that would make clear that there is no expected regression?

I wouldn't know. I just saw the new version had the mentioned functions. I haven't looked to see if they have backported them to a v2.x version.

**Comment by sirlatrom** [comment]
> Hello @sirlatrom,
> 
> Thanks for your contribution!
> 
> I'm wondering about potential regressions.
> Since it's a major version change, can you provide a diff of something that would make clear that there is no expected regression?

Otherwise read this paragraph: https://github.com/Masterminds/sprig/blob/master/README.md#package-versions

>>>>
## Package Versions

There are two active major versions of the `sprig` package.

* v3 is currently stable release series on the `master` branch. The Go API should
  remain compatible with v2, the current stable version. Behavior change behind
  some functions is the reason for the new major version.
* v2 is the previous stable release series. It has been more than three years since
  the initial release of v2. You can read the documentation and see the code
  on the [release-2](https://github.com/Masterminds/sprig/tree/release-2) branch.
  Bug fixes to this major version will continue for some time.
>>>>

**Comment by rtribotte** [comment]
Thanks for your feedback @sirlatrom 

Here's the link for changelog between versions https://github.com/Masterminds/sprig/compare/v2.22.0...v3.2.0

Do you know what functions are impacted by the "behavior change" between v2 and v3?

**Comment by sirlatrom** [comment]
> Do you know what functions are impacted by the "behavior change" between v2 and v3?

@rtribotte Unfortunately, I don't. I've been trying to see what essential difference there are between v2 and v3, and all I can see is that more functions have been added to the "defaults.go" file: https://github.com/Masterminds/sprig/compare/v2.22.0...v3.2.0#diff-1b38200ba9e5f4b19a852f1c2a6938de5e1546bc2a02aaa431dc34c1574687e8, notably an `init` function that runs `rand.Seed(time.Now().UnixNano())`, which might cause trouble if other code using this library does something similar, but different. There are also some simplifications of the numeric functions such as [toFloat64](https://github.com/Masterminds/sprig/compare/v2.22.0...v3.2.0#diff-666422347d41d7d3c123c923e83138ac9fd4763f59facfdbee352dc98c063711R14-R16) et al., and some additional `mustFoo` variants of functions in `list.go`.

**Review by jbdoumenjou — APPROVED** [review]
LGTM :+1:

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by rtribotte — APPROVED** [review]
LGTM 👌

**Pull request merged**
