### PR TITLE
add postgres StartTLS proxying

### PR DESCRIPTION
**Pull request by maigl**
### What does this PR do?

This adds postgres starttls support which allows to reverse proxy postgres connections through Traefik (via SNI).

Related to #7366

### Motivation

I'm part of a team that provides managed databases inside our company.
We needed to reverse-proxy many databases and to do this we use Traefik enhanced with this feature successfully for almost 2 years now.

#### Context:

We have a number of PostgreSQL databases running inside our kubernetes cluster.
All database instances are accessed through Traefik via a single IP address. In order to
access the right PostgreSQL instances from the clients we want to use different subdomains.
One subdomain should be the target address of a specific PostgreSQL instance and we want to
route to it via the SNI (server name indication in TLS header).
This approach seems to be the only possible solution in our setup. We don't have any other information
to identify the target PostgreSQL instance from a client request as it is a tcp connection and not http-based.

#### Problem:

PostgreSQL performs a StartTLS handshake before sending any TLS header. Since Traefik doesn't perform
this handshake no TLS header is sent and hence Traefik cannot extract the target server name.

#### Idea:

We propose the following steps:

- Traefik simulates a PostgreSQl server and performs StartTLS handshake with client
client now sends TLS header
- Traefik extracts SNI
- Traefik performs StartTLS handshake with server
- Traefik routes connection from client to target PostgreSQL instance

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

Other starttls flavors might be added in future. 

<sub>Michael Kuhnt <michael.kuhnt@daimler.com> Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))
</sub>

### CODE REVIEW

**Comment by maigl** [comment]
@ldez and @rtribotte I created the pr from a fresh fork directy from traefik/traefik, I only changed the title. The checkmark 'allow edits for maintainers .. ' is set. I hope I did it right this time.

**Comment by tfny** [comment]
Just a quick update, we are still reviewing.

**Comment by dani** [comment]
Do I understand it correctly that this PR would only allow passthrough connexion to postgres ? Or would traefik also be able to do the TLS termination and use either plain TCP or separated TLS to the postgres server ?

**Comment by rtribotte** [comment]
Hello @dani,

We are working on an alternative implementation, that should supersede this PR soon.
The support we are targeting will only be done for Postgres STARTTLS, and it will be possible to do both TLS termination and passthrough.

**Comment by rtribotte** [comment]
Since PR https://github.com/traefik/traefik/pull/9377 has been opened, we are closing this PR.

**Pull request closed without merging**
