### PR TITLE
feat(accesslogs): allow filter accesslogs by service names whitelist

### PR DESCRIPTION
**Pull request by ttys3**
### What does this PR do?

Enhancements

allow filter accesslogs by service names whitelist

like this:

```yaml
# Configuring Multiple Filters
accessLog:
  filePath: "/path/to/access.log"
  format: json
  filters:
    serviceNames:
      - "service1@file"
      - "service2@consulcatalog"
      - "service3@consulcatalog"
  ```

### Motivation

we have traefik which proxy api requests to all kinds of service, its a very heavy server, we do not want traefik write all the logs,  only a few kind of important service we want access logs.

currently there's no way to filter like this in traefik.

### More

- [x] Added/updated tests
- [x] Added/updated documentation

### CODE REVIEW

**Comment by rtribotte** [comment]
Hello @ttys3,

Thanks for this contribution!

As this would be an enhancement, the changes should target the master branch for the next v3 minor version.

Should the filtering of access logs be configurable statically, at least only, since services are dynamic resources?
We are unsure if this is the best approach, WDYT?

**Comment by ttys3** [comment]
> Hello @ttys3,
> 
> Thanks for this contribution!
> 
> As this would be an enhancement, the changes should target the master branch for the next v3 minor version. Could you please rebase it?
> 
> Should the filtering of access logs be configurable statically, at least only, since services are dynamic resources? We are unsure if this is the best approach, WDYT?

rebased and change target to master

Yes, I agree that static array filters would be a little not extenable.

I'd glad to change it from `ServiceNames  []string` to something like `ServiceNamePatterns  []string`

so people could use regex to match service names, but compared to static array filters, this will need a little more cpu.

do you think it is better to change it to regex ?

**Comment by rtribotte** [comment]
Hello @ttys3,

I was implying that the current option is static, meaning the configuration won't change at runtime and that this could be a limitation because one could not often dress the list of service names before they exist. Also, with some providers, the service name is determined automatically, so it would be difficult to list them beforehand (even with regular expression support).
I suggest controlling whether to enable access-logs for a given service based on its configuration, WDYT?

**Comment by ttys3** [comment]
> Hello @ttys3,
> 
> I was implying that the current option is static, meaning the configuration won't change at runtime and that this could be a limitation because one could not often dress the list of service names before they exist. Also, with some providers, the service name is determined automatically, so it would be difficult to list them beforehand (even with regular expression support). I suggest controlling whether to enable access-logs for a given service based on its configuration, WDYT?

do you mean use access-logs as dynamic middleware ?

**Comment by rtribotte** [comment]
Hello @ttys3,

No, it shouldn't be an access-log middleware, my suggestion is to be able to opt-out inside the service configuration, with something like:
```yaml
services:
    service1:
        accesslogs: false
```

I apologize for the misunderstanding, I should have been more specific in my proposal.

**Comment by ttys3** [comment]
the problem is `service1`, in file provider, we always write static service name, it is no problem here.

but in dynamic provider, like consul,  

according to the doc https://doc.traefik.io/traefik/v3.0/routing/providers/consul-catalog/#services

for example, we must config a tag(label) like this:

```
traefik.http.services.{name-of-your-choice}.accesslogs=false
```

for example

```
traefik.http.services.service1.accesslogs=false
```

the problem is, is this OK to write the `service1`? Because the service name is basically auto calculated.

**Comment by rtribotte** [comment]
Hello @ttys3,

Actually, the file provider is no different from any other and produces a dynamic configuration that can be updated at runtime.

In fact, in order to provide a configuration for a service, it needs to be "named", which in the case of "orchestrator" providers, somewhat defeats the purpose of automatic service discovery and hence naming.
But it is no different for any service configuration options, it would not create precedence.

Perhaps it's a hint that this configuration should belong to the router, not the service. I'm not sure, both make sense in my opinion.

WDYT?

**Comment by ttys3** [comment]
close due to https://github.com/traefik/traefik/pull/11308 already meet the need

**Pull request closed without merging**
