### PR TITLE
fix: consulcatalog to update before the first interval

### PR DESCRIPTION
**Pull request by greut**
### What does this PR do?

It fixes the behavior of the consul catalog provider w.r.t. how it polls Consul. It currently waits the refreshing interval before doing its first pull which causes many 404 for too long.

### Motivation

A colleague thinks that Traefik v2 is not ready yet for us, currently on Traefik v1. He'll highly motivated to fix all the remaining issues we may encounter.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

:heart:

### CODE REVIEW

**Comment by kevinpollet** [comment]
Hello @greut,

Thanks for your contribution!

We think that your PR is a `bugfix`.
Therefore, can you rebase your PR on the `v2.3` branch?

**Comment by greut** [comment]
@kevinpollet let me know if you see some kind of integration test that would make sense here.

**Comment by kevinpollet** [comment]
It seems that the `v2.3` branch you have rebased onto is out of date and that's why the integration tests are failing.

Can you update your branch and rebase your PR accordingly?

**Comment by greut** [comment]
much better indeed.

**Review by kevinpollet — APPROVED** [review]
LGTM 👍

**Review by dtomcej — APPROVED** [review]
LGTM
:shipit:

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Pull request merged**
