### PR TITLE
Propose kevinpollet to Maintainers

### PR DESCRIPTION
**Pull request by SantoDE**
### What does this PR do?

Propose @kevinpollet to be promoted to be a maintainer

### Motivation

🎉

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

**Review by rtribotte — APPROVED** [review]
LGTM 🎉

**Review by jbdoumenjou — APPROVED** [review]
LGTM :rocket:

**Review by dtomcej — APPROVED** [review]
LGTM
:shipit:

**Review by ldez — APPROVED** [review]
:crossed_swords:

**Review by nmengin — APPROVED** [review]
LGTM

**Pull request merged**
