### PR TITLE
Watch for Consul events to rebuild the dynamic configuration

### PR DESCRIPTION
**Pull request by JasonWangA**
### What does this PR do?

It allows the configuration to be reloaded on Consul events.

### Motivation

To be able to only reload the configuration when it is actually necessary, and decrease the frequency of requests to the Consul server.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes
Co-authored-by: Kevin Pollet <pollet.kevin@gmail.com>
Co-authored-by: Romain <rtribotte@users.noreply.github.com>

### CODE REVIEW

**Comment by m1keil** [comment]
Hello, very curious to know in what state is this PR in and what are the odds of seeing this merged in the near future?

**Comment by kevinpollet** [comment]
Hello,
 
This pull request is labelled in `needs-design-review`, and as you can see in our [contribution guide](https://github.com/traefik/contributors-guide/blob/master/review_guidelines.md), this means that we have to take a closer look at the scope of impact for that pull request. 

We will come back soon when we did the first design review iteration.

**Comment by JasonWangA** [comment]
> Hello,
> 
> This pull request is labelled in `needs-design-review`, and as you can see in our [contribution guide](https://github.com/traefik/contributors-guide/blob/master/review_guidelines.md), this means that we have to take a closer look at the scope of impact for that pull request.
> 
> We will come back soon when we did the first design review iteration.

Hope you have any feedback ASAP.

**Comment by tfny** [comment]
Thanks for checking in! This PR is under review.  Unfortunately, because of the backlog of PRs, this review may take up to 3 months to be completed.

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by rtribotte — APPROVED** [review]
Thanks 👍

**Review by mpl — APPROVED** [review]

**Pull request merged**
