### PR TITLE
Refactor configuration reload/throttling

### LINKED ISSUE #6632: Ensure that configurationValidatedChan ever receives the latest different configuration from each provider
### Do you want to request a *feature* or report a *bug*?

Feature / Enhancement

### What did you expect to see?

I was debugging issue #6626 and meanwhile noticed that configurationValidatedChan channel is buffered, which means, that if during configuration reload, even due to throttling and same configuration checks present, it is still possible to enqueue a flapping state.

Imagine as:

```
| Reload time
+----------------------------------------------------------------------------------------+
+-- throttling --+-- throtrling --+-- throttling --+-- throttling --+-- throttling --+
c1               c2               c1               c2               c1               c2
```

So, if a reload takes multiple throttling time intervals, then you can see, that different c1 and c2 configurations will be enqueued, and with long relad times, will cause services flapping long after
they became stable in real.

I've already refactored the relevant parts, but still needs some cleanup. Is it worth to create a PR?

### PR DESCRIPTION
**Pull request by rkojedzinszky**
### What does this PR do?

Refactor configuration reload throttling/processing to remove configuration flapping, and to improve responsiveness under high input from (a) provider(s).

### Motivation

Some scenarios around the handling and reloading of configurations were not behaving well. Notably,
1) when receiving an alternation of recurring configurations, it is useless and costly to load the intermediate configuration states (configuration flapping).
2) when receiving lots of configurations from one (or several) provider(s) for an extended duration, the incurred stress on the configuration watcher was such that none, or at least not enough, configurations were actually reloaded.

In addition, in the past the providersThrottleDuration option (either user-set or through its default value) was applied to all the providers, including some internal ones, such as the TLS ALPN acme challenge one. This was problematic because when one wanted to throttle high input providers (e.g. Kubernetes), one would also implicitly throttle the acme one, which is not desirable if one wants a responsive certificates renewal system.

Therefore, this PR, through a refactoring of the whole throttling and reloading of configuration addresses the problems described above. And notably, it introduces a new abstraction which allows the throttling to be applied independently to each provider. For example, in the current state, there never is any throttling applied to the TLS ALPN acme one.

Fixes #6632

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Co-authored-by: Mathieu Lonjaret <mathieu.lonjaret@gmail.com>
Co-authored-by: Romain rtribotte@users.noreply.github.com

### CODE REVIEW

**Comment by juliens** [comment]
Thx for your PR!

Could you provide us a unit test to show us the use case it should handle?

**Comment by rkojedzinszky** [comment]
> Thx for your PR!
> 
> Could you provide us a unit test to show us the use case it should handle?

I will need time for that, but please check https://github.com/containous/traefik/issues/6632#issue-593783690

**Comment by rtribotte** [comment]
Hello @rkojedzinszky,

We took the liberty of experimenting and iterating on the PR.
We hope that's ok.

**Comment by rkojedzinszky** [comment]
> Hello @rkojedzinszky,
> 
> We took the liberty of experimenting and iterating on the PR.
> We hope that's ok.
> 
> WDYT?

Sure. Happy to see that the PR is interesting.

**Comment by mpl** [comment]
Hello @rkojedzinszky ,

Could you please let us know if this new version of the PR as it is right now fixes the issue for you? In particular, if it works for the flapping state problem?

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Review by rtribotte — APPROVED** [review]
Thanks 👍

**Review by mpl — APPROVED** [review]

**Pull request merged**
